In [1]:
from instat_to_wyscout_pandas import *

In [2]:
df=pandas_transform("data/InStat_AXA_Super_2023-06-02_Switzerland. AXA Women's Super League_Servette Chenois_vs_Zurich_2582307_2023-06-02_Servette Chenois_vs_Zurich_2582307_rawdata - Kopie.xml")

c:\Users\Rui\BA\Instat_toWyscout_transform\instat_to_wyscout_pandas.py:259: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wyscoutdf = pd.concat([wyscoutdf, pd.DataFrame([event])], ignore_index=True)

In [4]:
df[['type.primary','type.secondary', 'matchTimestamp', 'player.name', 'groundDuel.duelType', 'aerialDuel.opponent.name', 'matchPeriod']].iloc[0:780]

,type.primary,type.secondary,matchTimestamp,player.name,groundDuel.duelType,aerialDuel.opponent.name,matchPeriod
0,pass,"[back_pass, short_or_medium_pass]",0:00:00.000,Paula Serrano Castano,NaN,NaN,1H
1,pass,"[forward_pass, pass_to_final_third, loss, long...",0:00:02.510,Nahla Elodie Nakkach,NaN,NaN,1H
2,game_interruption,[ball_out],0:00:08.490,None,NaN,NaN,1H
3,pass,"[forward_pass, loss, short_or_medium_pass]",0:00:18.810,Julia Stierli,NaN,NaN,1H
4,game_interruption,[ball_out],0:00:20.940,None,NaN,NaN,1H
...,...,...,...,...,...,...,...
775,offside,"[loss, touch_in_box]",0:45:17.190,Sandrine Mauron,NaN,NaN,2H
776,free_kick,[],0:45:44.250,Seraina Friedli,NaN,NaN,2H
777,duel,"[dribble, defensive_duel, aerial_duel]",0:45:46.540,Nahla Elodie Nakkach,NaN,Marie-Therese Hobinger,2H
778,duel,"[offensive_duel, aerial_duel]",0:45:46.540,Marie-Therese Hobinger,NaN,Nahla Elodie Nakkach,2H
779,pass,"[loss, short_or_medium_pass]",0:45:46.540,Nahla Elodie Nakkach,NaN,NaN,2H